const express=require("express")
const app=express()
const cors=require("cors")
app.use(cors())
app.use(express.json())
const custrouter=require("./routers/cust.routes")
const stockrouter=require("./routers/stock.router")
const addRouter = require('./routers/add.routes')
const historyrouter=require("./routers/history.routes")
app.use("/customer",custrouter)
app.use("/stock",stockrouter)
app.use("/addlist",addRouter)
app.use("/history",historyrouter)
module.exports=app;